x <- tskit_example()
expect_true(S7::S7_inherits(x, TreeSequence))

info <- tskit_summary(x)
expect_identical(info$sequence_length, 10)
expect_identical(info$trees, 1)
expect_identical(info$samples, 2)
expect_identical(info$nodes, 3)
expect_identical(info$edges, 2)
expect_identical(info$sites, 1)
expect_identical(info$mutations, 1)
expect_identical(tskit_samples(x), 0:1)

nodes <- tskit_nodes(x)
expect_identical(nodes$id, 0:2)
expect_identical(nodes$time, c(0, 0, 1))
expect_identical(nodes$population, rep(-1L, 3L))

edges <- tskit_edges(x)
expect_identical(edges$id, 0:1)
expect_identical(edges$left, c(0, 0))
expect_identical(edges$right, c(10, 10))
expect_identical(edges$parent, c(2L, 2L))
expect_identical(edges$child, 0:1)

trees <- tskit_trees(x)
expect_identical(trees$index, 0L)
expect_identical(trees$left, 0)
expect_identical(trees$right, 10)
expect_identical(trees$roots, 1)
expect_identical(trees$edges, 2)

path <- tempfile(fileext = ".trees")
expect_identical(tskit_dump(x, path), normalizePath(path, winslash = "/"))
expect_error(tskit_dump(x, path), "already exists")
y <- tskit_load(path)
expect_identical(tskit_summary(y), info)
expect_identical(tskit_nodes(y), nodes)
expect_identical(tskit_edges(y), edges)
unlink(path)

expect_error(tskit_load(tempfile()), "path")
expect_error(tskit_nodes(list()), "TreeSequence")
